import { SiteFrame } from "../site-frame";

export const metadata = { title: "Tutorial | BridgeHub" };

// Only set after the public deployment is verified. Static content uses this at build time.
function publicEndpoint() {
  const value = process.env.BRIDGEHUB_PUBLIC_ORIGIN;
  if (!value) return null;
  try {
    const url = new URL(value);
    if (url.protocol !== "https:" || url.username || url.password || url.search || url.hash || url.pathname !== "/") return null;
    return `${url.origin}/api/mcp`;
  } catch { return null; }
}

export default function Tutorial() {
  const endpoint = publicEndpoint();
  return <SiteFrame current="Tutorial">
    <div className="page-heading"><p className="eyebrow">GET CONNECTED / WINDOWS POWERSHELL</p><h1>Your first company lookup.</h1><p className="lede">Connect Codex CLI to BridgeHub, then ask for an SEC company profile with traceable sources.</p><p className="small muted">BridgeHub needs no end-user account, virtual key, or OpenAI API key. Codex has its own installation, sign-in, and account-access requirements.</p></div>
    <section className="tutorial-step"><span className="step-number" aria-hidden="true">01</span><div><h2>Prepare Codex CLI</h2><p>Use Windows PowerShell with Node.js and npm installed. This project requires Node.js 22.14 or newer. Install Codex CLI following the <a href="https://learn.chatgpt.com/docs/codex/cli">official installation guide</a>, then open a new PowerShell window.</p><pre><code>{'codex --version\ncodex'}</code></pre><p>On first launch, follow Codex’s sign-in flow using an account with Codex access. Complete any Windows setup prompts. When ready, exit Codex with <code>/quit</code> to run the connection command below.</p></div></section>
    <section className="tutorial-step"><span className="step-number" aria-hidden="true">02</span><div><h2>Choose where to connect</h2><h3>Local demo · on your computer</h3><p>Open PowerShell in the BridgeHub project folder. For a first-time checkout, run <code>npm ci</code>, copy <code>.env.example</code> to <code>.env.local</code>, and set <code>SEC_CONTACT_EMAIL</code> to the operator’s real contact email. Keep that file private. If setup is already complete, just run:</p><pre><code>npm run dev</code></pre><p><strong>Keep this terminal running.</strong> Open <a href="http://127.0.0.1:3000">http://127.0.0.1:3000</a> to read the website. In a second PowerShell window, add the MCP endpoint:</p><pre><code>codex mcp add bridgehub --url http://127.0.0.1:3000/api/mcp</code></pre><p>Local development does not require Redis. The address refers to your own computer; it cannot connect another person to your server. If the server chooses another port, use that port in the command.</p><h3>Public demo · hosted service</h3>{endpoint ? <><p>Use this configured public endpoint instead of localhost. You do not need the BridgeHub project or a local development server.</p><pre><code>{`codex mcp add bridgehub --url ${endpoint}`}</code></pre></> : <div className="notice"><strong>Public endpoint not published yet.</strong><p>Use the local instructions for now. After publication, this section will show the configured public address and its connection command. There is no public address to connect to yet.</p></div>}<p>If <code>bridgehub</code> already exists, inspect it with <code>codex mcp get bridgehub</code>. To switch endpoints, remove that entry with <code>codex mcp remove bridgehub</code>, then run the desired add command. Other MCP entries remain unchanged.</p></div></section>
    <section className="tutorial-step"><span className="step-number" aria-hidden="true">03</span><div><h2>Check the connection</h2><pre><code>{'codex mcp list\ncodex'}</code></pre><p>The list confirms saved configuration. In a fresh Codex session, enter <code>/mcp</code> to check the active connection. Confirm BridgeHub exposes <code>us_search_sec_company</code>. BridgeHub requires no MCP OAuth login; an unsupported-authentication label by itself is not a connection failure.</p><p>These commands follow <a href="https://learn.chatgpt.com/docs/extend/mcp?surface=cli">official Codex MCP guidance</a>. Follow any tool-use approval prompts shown by your Codex configuration.</p></div></section>
    <section className="tutorial-step"><span className="step-number" aria-hidden="true">04</span><div><h2>Ask for Apple</h2><blockquote className="prompt">Use BridgeHub’s us_search_sec_company tool to search AAPL. Summarize the company profile and include the official source URLs and retrieval times.</blockquote><p>Look for a real tool invocation and Apple’s CIK <code>0000320193</code>. The response should include profile provenance and, for AAPL search, directory provenance. Filing counts and timestamps can change. A reply from model memory alone does not verify the connection.</p></div></section>
    <section className="content-section"><h2>If something goes wrong</h2><div className="two-column"><div><h3>Codex or endpoint unavailable</h3><p>If <code>codex</code> is not recognized, finish the official CLI installation and reopen PowerShell. If PowerShell blocks an installed script, try its <code>codex.cmd</code> launcher when present. For local connection errors, confirm the dev server is running and the address includes <code>/api/mcp</code>. Restart Codex after changing configuration.</p><h3>Tool not visible</h3><p>Check <code>codex mcp get bridgehub</code> and <code>/mcp</code>. A saved server entry does not prove it is reachable. Managed Codex installations may restrict MCP servers; check with your administrator if policy blocks the connection.</p></div><div><h3>Request limits</h3><p><code>rate_limited</code> is BridgeHub’s shared limit of 10 searches per rolling minute. Wait for the indicated delay. <code>upstream_rate_limited</code> comes from SEC. BridgeHub also allows at most five SEC request starts per rolling second and waits only within a 30-second lookup budget.</p><h3>Data unavailable or incomplete</h3><p><code>service_unavailable</code> means the operator must check shared storage. SEC blocking, timeouts, and unavailable data have separate error categories. Retry later when marked retryable; a persistent block needs an operator check. For <code>partial</code>, read the warnings and failed CIKs before using the results.</p></div></div></section>
  </SiteFrame>;
}
